image: Visual Studio 2019  # образ для сборки

stack: node 18  # окружение

branches:
  only:
    - task5_4  # ветка git
clone_folder: E:\Netologe\NetologeJavaScript\ci-template
cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint && npm test  # скрипт тестирования
